spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: user
        password: bitnami
        listener:
            simple:
                retry:
                    enabled: true
                    initial-interval: 3s
                    max-attempts: 1
                    max-interval: 10s
                    multiplier: 2
    data:
        mongodb:
            authentication-database: admin
            database: lavanda
            host: localhost
            password: example
            port: 27017
            username: root
filebot:
    path:
        input: /Users/luiscarlosjimenezlopez/Documents/Github/LavandaDelPatio/filebot-executor/src/main/resources
        # src/main/resources/filebot
        output: src/main/resources/filebot_output
        data: src/main/resources/filebot_data
    test:
        enabled: true    
server.port: 8080   